# https://config.travis-ci.com/explore
os: linux
dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  global:
    - XDEBUG_MODE="coverage"
  jobs:
#    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""


install:
  - composer self-update && composer --version

before_script:
  - php -i
  - composer validate --no-check-all --strict
  - composer update $PREFER_LOWEST

script:
#  - php testsuite.php --ci
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover