os: linux
dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php:
        nightly
  include:
    - php: nightly
      env: IGNORE_PLATFORM_REQS="--ignore-platform-reqs"

env:
  jobs:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""


install:
  - composer self-update && composer --version

before_script:
  - php -i
  - composer validate --no-check-all --strict
  - composer update $PREFER_LOWEST $IGNORE_PLATFORM_REQS

script:
#  - php testsuite.php --ci
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover