language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

matrix:
  fast_finish: true

# faster builds on new travis containers
sudo: false

install:
  - composer self-update && composer --version
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
