#!/usr/bin/env php
<?php
/**
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @license
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * phpWhois console client
 * If you want to make it available for all users, type (under root):
 * # ln -s [path to this script] /usr/local/bin/
 *
 * Then use it like
 * $ phpwhois example.com
 *
 * @link http://phpwhois.pw
 * @copyright Copyright (c) 2015 Dmitry Lukashin
 */

define('PATH', dirname(__FILE__));

if (php_sapi_name() != 'cli') {
    echo "\nThis script can only be started from the terminal\n";
    exit(1);
}

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} else {
    echo "\nCan't find vendor/ dir. Run composer install first\n";
    exit(2);
}

if ($argc != 2) {
    print_usage();
    exit(1);
}

try {
    $whois = new \phpWhois\Whois($argv[1]);
    $response = $whois->lookup();
    echo $response->getRaw();
    echo "\nPhpWhois info:\n\n";
    foreach ($response->getParsed()['dates'] as $key => $value) {
        echo "$key: ".(($value) ? date('c', $value) : '[NOT FOUND]')."\n";
    }
    echo "\n";
} catch (\Exception $e) {
    echo "\n".$e->getMessage()."\n\n";
    exit(1);
}

/**
 * Print usage help
 */
function print_usage()
{
    global $argv;
    echo <<<USAGE

USAGE:
$argv[0] [domain]


USAGE;
}